create table public.projects (
  id bigint generated by default as identity not null,
  owner_id uuid not null default gen_random_uuid (),
  content json null,
  public boolean null,
  created_at timestamp with time zone not null default now(),
  name character varying not null,
  share_token text null,
  constraint projects_pkey primary key (id)
) TABLESPACE pg_default;